#include "libriot.h"

char const *RIOT_IO_ERROR_NAME_MAP[_RIOT_IO_ERROR_COUNT] = {
	[RIOT_IO_ERROR_OK]	= "RIOT_IO_ERROR_OK",
	[RIOT_IO_ERROR_EOF]	= "RIOT_IO_ERROR_EOF",
	[RIOT_IO_ERROR_ALLOC]	= "RIOT_IO_ERROR_ALLOC",
	[RIOT_IO_ERROR_CORRUPT]	= "RIOT_IO_ERROR_CORRUPT",
};
